# Build stage
FROM maven:3.6.3-jdk-8 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:resolve
COPY src/ /app/src/
RUN mvn package

# Production stage
FROM openjdk:8-jre-slim
WORKDIR /app/target

EXPOSE 8080
USER 1000
CMD ["java", "-jar", "tacs-1c-2023-1.0-SNAPSHOT-jar-with-dependencies.jar"]
