name: Deploy

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    - uses: azure/docker-login@v1
      with:
        login-server: tptacs.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker compose build
        docker compose push
